[package]
name = "founder"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
bstr = "0.2.8"
duct = "0.13.0"
os_pipe = "0.9.0"
crossbeam-utils = "0.6.6"
